analyzer:
  errors:
    depend_on_referenced_packages: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_locals: true
    always_declare_return_types: true
    prefer_single_quotes: true
    unnecessary_this: true
    directives_ordering: true
    sort_child_properties_last: true
    use_key_in_widget_constructors: true
